# Generated by Django 3.2 on 2021-05-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210503_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='UGChords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=1000)),
                ('song', models.CharField(max_length=1000)),
                ('ug_chords', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
